### ISSUE TITLE
Unhandled Panic

### ISSUE THREAD

**Issue by peterjan** [SiaFoundation/action-golang-analysis#2]
I recently found out `japecheck` was throwing a panic for a while now, and we didn't catch it because our CI didn't fail. I think this action has to be updated to recover from a potential panic and report an error when it happens. I'm not terribly familiar with the codebase but it looks like we could adjust `parseAnalyzerOutput` to check for a potential panic.

**Comment by lukechampine** [comment]
cc @chris124567
